<#
.SYNOPSIS
    Setup PowerShell profile to auto-activate Claudine polyglot environment

.DESCRIPTION
    Configures PowerShell profile ($PROFILE) to automatically source claudineENV.ps1
    when opening a terminal in the Claudine workspace. Handles:
    
    - Workspace detection (only activates if in Claudine directory)
    - VS Code Extension Host terminals (-NoProfile flag workaround)
    - Existing profile preservation (appends, doesn't overwrite)
    - Idempotent setup (safe to run multiple times)
    
.PARAMETER Force
    Overwrite existing Claudine profile section if present

.PARAMETER Uninstall
    Remove Claudine profile section from $PROFILE

.EXAMPLE
    .\Setup-ClaudineProfile.ps1
    
    Adds Claudine auto-activation to your PowerShell profile

.EXAMPLE
    .\Setup-ClaudineProfile.ps1 -Force
    
    Overwrites existing Claudine profile section

.EXAMPLE
    .\Setup-ClaudineProfile.ps1 -Uninstall
    
    Removes Claudine profile section

.NOTES
    File: Setup-ClaudineProfile.ps1
    Version: 1.0.0
    Author: Claudine Supreme Consciousness Nexus
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [switch]$Force,
    
    [Parameter(Mandatory = $false)]
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

# DYNAMIC PATH RESOLUTION - Detect repository root dynamically
. (Join-Path $PSScriptRoot "Get-RepositoryRoot.ps1")
$ClaudineWorkspace = Get-RepositoryRoot -StartPath $PSScriptRoot
$ClaudineEnvScript = Join-Path $ClaudineWorkspace "scripts\claudineENV.ps1"
$ProfilePath = $PROFILE
$ProfileMarkerStart = "# ═══ CLAUDINE AUTO-ACTIVATION START ═══"
$ProfileMarkerEnd = "# ═══ CLAUDINE AUTO-ACTIVATION END ═══"

# Profile code block (what gets inserted)
# IMPORTANT: This code uses Get-RepositoryRoot dynamically, not hardcoded paths
$ProfileCode = @"
$ProfileMarkerStart
# Auto-activate Claudine polyglot environment when in workspace
# Generated by: Setup-ClaudineProfile.ps1 v2.0.0 (Portable/Isolated)
# Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

# DYNAMIC DETECTION: Find Claudine workspace via .git folder traversal
# This makes the profile portable across machines, users, and repository locations

# Strategy 1: Use git command if available
`$claudineWorkspace = `$null
if (Get-Command git -ErrorAction SilentlyContinue) {
    try {
        `$gitRoot = git rev-parse --show-toplevel 2>`$null
        if (`$gitRoot -and (Test-Path `$gitRoot)) {
            `$claudineWorkspace = `$gitRoot -replace '/', '\'
        }
    } catch { }
}

# Strategy 2: Walk up from PWD looking for .git + scripts\claudineENV.ps1
if (-not `$claudineWorkspace) {
    `$currentPath = `$PWD.Path
    `$maxDepth = 10
    `$depth = 0
    
    while (`$depth -lt `$maxDepth) {
        `$gitPath = Join-Path `$currentPath ".git"
        `$envScript = Join-Path `$currentPath "scripts\claudineENV.ps1"
        
        if ((Test-Path `$gitPath) -and (Test-Path `$envScript)) {
            `$claudineWorkspace = `$currentPath
            break
        }
        
        `$parent = Split-Path `$currentPath -Parent
        if (-not `$parent -or `$parent -eq `$currentPath) { break }
        
        `$currentPath = `$parent
        `$depth++
    }
}

# Only activate if workspace detected and not already activated
if (`$claudineWorkspace -and 
    (-not `$env:CLAUDINE_ACTIVATED) -and 
    (Test-Path (Join-Path `$claudineWorkspace "scripts\claudineENV.ps1"))) {
    
    # Silent activation (fast startup)
    try {
        `$claudineEnvScript = Join-Path `$claudineWorkspace "scripts\claudineENV.ps1"
        . `$claudineEnvScript -Quiet
        Write-Host "🔥💋 Claudine polyglot environment activated" -ForegroundColor Magenta
    } catch {
        Write-Host "⚠️  Claudine activation failed: `$_" -ForegroundColor Yellow
    }
}
$ProfileMarkerEnd
"@

# ═══════════════════════════════════════════════════════════════════════════════
# MAIN LOGIC
# ═══════════════════════════════════════════════════════════════════════════════

Write-Host "`n╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  🔥💋 CLAUDINE PROFILE SETUP 💋🔥                           ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════════╝`n" -ForegroundColor Cyan

# Ensure profile directory exists
$profileDir = Split-Path $ProfilePath -Parent
if (-not (Test-Path $profileDir)) {
    Write-Host "📁 Creating profile directory: $profileDir" -ForegroundColor Cyan
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

# Read existing profile (or empty string if doesn't exist)
$existingProfile = if (Test-Path $ProfilePath) {
    Get-Content $ProfilePath -Raw
} else {
    ""
}

# Check if Claudine section already exists
$hasClaudineSection = $existingProfile -match [regex]::Escape($ProfileMarkerStart)

# ═══════════════════════════════════════════════════════════════════════════════
# UNINSTALL MODE
# ═══════════════════════════════════════════════════════════════════════════════

if ($Uninstall) {
    if (-not $hasClaudineSection) {
        Write-Host "✅ Claudine profile section not found (nothing to uninstall)" -ForegroundColor Green
        return
    }
    
    Write-Host "🗑️  Removing Claudine profile section..." -ForegroundColor Yellow
    
    # Remove everything between markers (inclusive)
    $pattern = "(?s)$([regex]::Escape($ProfileMarkerStart)).*?$([regex]::Escape($ProfileMarkerEnd))"
    $newProfile = $existingProfile -replace $pattern, ""
    
    # Clean up extra newlines
    $newProfile = $newProfile -replace "`n{3,}", "`n`n"
    
    Set-Content -Path $ProfilePath -Value $newProfile.TrimEnd() -NoNewline
    
    Write-Host "✅ Claudine profile section removed!" -ForegroundColor Green
    Write-Host "`n📝 Profile path: $ProfilePath" -ForegroundColor Gray
    return
}

# ═══════════════════════════════════════════════════════════════════════════════
# INSTALL MODE
# ═══════════════════════════════════════════════════════════════════════════════

if ($hasClaudineSection -and -not $Force) {
    Write-Host "⚠️  Claudine profile section already exists!" -ForegroundColor Yellow
    Write-Host "`n📝 To update, run with -Force flag:" -ForegroundColor Gray
    Write-Host "   .\Setup-ClaudineProfile.ps1 -Force" -ForegroundColor Cyan
    Write-Host "`n📝 To remove, run with -Uninstall flag:" -ForegroundColor Gray
    Write-Host "   .\Setup-ClaudineProfile.ps1 -Uninstall" -ForegroundColor Cyan
    return
}

if ($hasClaudineSection -and $Force) {
    Write-Host "🔄 Updating existing Claudine profile section..." -ForegroundColor Yellow
    
    # Remove old section
    $pattern = "(?s)$([regex]::Escape($ProfileMarkerStart)).*?$([regex]::Escape($ProfileMarkerEnd))"
    $existingProfile = $existingProfile -replace $pattern, ""
}

# Append Claudine section
$newProfile = if ([string]::IsNullOrWhiteSpace($existingProfile)) {
    $ProfileCode
} else {
    # Ensure proper spacing
    $existingProfile.TrimEnd() + "`n`n" + $ProfileCode
}

Write-Host "📝 Writing profile configuration..." -ForegroundColor Cyan
Set-Content -Path $ProfilePath -Value $newProfile -NoNewline

Write-Host "✅ Claudine profile setup complete!" -ForegroundColor Green

# ═══════════════════════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════

Write-Host "`n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
Write-Host "📊 SETUP SUMMARY" -ForegroundColor Yellow
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray

Write-Host "`n📄 Profile Path:" -ForegroundColor White
Write-Host "   $ProfilePath" -ForegroundColor Gray

Write-Host "`n🔧 Activation Script:" -ForegroundColor White
Write-Host "   $ClaudineEnvScript" -ForegroundColor Gray

Write-Host "`n📦 Workspace Detection:" -ForegroundColor White
Write-Host "   Auto-activates when PWD starts with:" -ForegroundColor Gray
Write-Host "   $ClaudineWorkspace" -ForegroundColor Cyan

Write-Host "`n⚡ Activation Mode:" -ForegroundColor White
Write-Host "   Silent (fast startup, minimal output)" -ForegroundColor Gray

Write-Host "`n🎯 Next Steps:" -ForegroundColor Yellow
Write-Host "   1. Open a NEW PowerShell terminal" -ForegroundColor White
Write-Host "   2. Navigate to Claudine workspace" -ForegroundColor White
Write-Host "   3. Environment will auto-activate!" -ForegroundColor White

Write-Host "`n💡 Tip: To load functions library automatically, edit your profile:" -ForegroundColor Cyan
Write-Host "   notepad `$PROFILE" -ForegroundColor Gray
Write-Host "   Change: -Quiet" -ForegroundColor DarkGray
Write-Host "   To:     -LoadFunctions" -ForegroundColor Green

Write-Host "`n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkGray
Write-Host "🔥💋 Claudine is ready to dominate your terminal sessions! 💋🔥" -ForegroundColor Magenta
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`n" -ForegroundColor DarkGray
